name: 'Test input'

on:
  workflow_dispatch:
    inputs:
      my-boolean:
        default: true
        type: boolean
        description: "select or don't!"
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event_name == "pull_request" && github.head_ref || github.event_name == "push" && github.ref_name || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  call:
    name: "sub"
    uses: ./.github/workflows/test-sub.yml
    with:
      my-bool: ${{ github.event.inputs.my-boolean }}
      my-bool3: