name: 'Test Sub'

on:
  workflow_call:
    inputs:
      my-bool:
        type: string
      my-bool2:
        type: string
        default: "true"
      my-bool3:
        type: string
        default: "false"
  push:
  pull_request:

jobs:
  run:
    name: "TNT"
    runs-on: ubuntu-latest
    steps:
      - name: true-or-false
        run: |
          if [[ -z "${{ inputs.my-bool }}" ]] || [[ "true" = "${{ inputs.my-bool }}" ]]; then
            echo "GO GO GO!"
          else
            echo "NO NO NO..."
          fi
          echo "my-bool:  '${{ inputs.my-bool }}'"
          echo "my-bool2: '${{ inputs.my-bool2 }}'"
          echo "my-bool3: '${{ inputs.my-bool3 }}'"
          echo "github.workflow: '${{ github.workflow }}'"
