name: 'Test Sub'

on:
  workflow_call:
    inputs:
      my-bool:
        type: boolean
      my-bool2:
        type: boolean
        default: true
jobs:
  run:
    name: "EKS"
    runs-on: ubuntu-latest
    steps:
      - name: true-or-false
        run: |
          if [[ -z "${{ inputs.my-bool }}" ]] || [[ "true" = "${{ inputs.my-bool }}" ]]; then
            echo "GO GO GO!"
          else
            echo "NO NO NO..."
          fi
          echo "my-bool:  '${{ inputs.my-bool }}'"
          echo "my-bool2: '${{ inputs.my-bool2 }}'"
