name: 'Test Sub'

on:
  workflow_call:
    inputs:
      my-bool:
        type: string
      my-bool2:
        type: string
        default: "true"
      my-bool3:
        type: string
        default: "false"
  push:
  pull_request:


# concurrency:
#   group: '${{ github.workflow }} @ ${{ github.event_name == "pull_request" && github.head_ref || github.event_name == "push" && github.ref_name || github.head_ref || github.ref }}'
#   cancel-in-progress: true

jobs:
  run:
    name: "TNT"
    runs-on: ubuntu-latest
    steps:
      - name: true-or-false
        run: |
          if [[ -z "${{ inputs.my-bool }}" ]] || [[ "true" = "${{ inputs.my-bool }}" ]]; then
            echo "GO GO GO!"
          else
            echo "NO NO NO..."
          fi
          echo "my-bool:  '${{ inputs.my-bool }}'"
          echo "my-bool2: '${{ inputs.my-bool2 }}'"
          echo "my-bool3: '${{ inputs.my-bool3 }}'"
          echo "github.workflow: '${{ github.workflow }}'"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checking stuff
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event_name == "pull_request" }}
          echo ${{ github.head_ref }}
      - name: sleep
        run: sleep 20

