name: 'Test input'

on:
  workflow_dispatch:
    inputs:
      my-boolean:
        default: true
        type: boolean
        description: "select or don't!"
  push:
    branches:
      - main

jobs:
  call:
    name: "sub"
    uses: ./.github/workflows/test-sub.yml
    with:
      my-bool: ${{ github.event.inputs.my-boolean }}
      my-bool3: